# Generated by Django 5.1.6 on 2025-03-11 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='users',
            field=models.ManyToManyField(related_name='member_of_channels', to=settings.AUTH_USER_MODEL, verbose_name='участники'),
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.channel', verbose_name='канал'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['channel', '-time_create'], name='messenger_m_channel_ac3b03_idx'),
        ),
    ]
