# Generated by Django 5.1.6 on 2025-03-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='приватный канал'),
        ),
    ]
