# Generated by Django 5.1.6 on 2025-04-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_channel_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='is_private',
            field=models.BooleanField(choices=[(0, 'Публичный'), (1, 'Приватный')], default=0, verbose_name='статус канала'),
        ),
    ]
