# Generated by Django 5.1.6 on 2025-04-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_channel_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-creation', 'name'], 'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
    ]
